@endpoint=https://0p6v7xaljd.execute-api.us-east-1.amazonaws.com/prod

POST {{endpoint}}/joborder/
Content-Type: application/json

{
    "username":"blu",
    "title":"This is a test",
    "content":[
        "this is 4\nthis 2\n    3        ",
        "this is 5"
    ]
    
}
###
